//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapperHoneyBadgersWebsite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BadgerDatabaseEntities : DbContext
    {
        public BadgerDatabaseEntities()
            : base("name=BadgerDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountEnt> AccountEnts { get; set; }
        public virtual DbSet<OrderItemEnt> OrderItemEnts { get; set; }
        public virtual DbSet<OrderEnt> OrderEnts { get; set; }
        public virtual DbSet<ProductEnt> ProductEnts { get; set; }
    }
}
