//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapperHoneyBadgersWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemEnt
    {
        public int OrderID { get; set; }
        public decimal ProductID { get; set; }
        public int Qty { get; set; }
    
        public virtual OrderEnt Order { get; set; }
        public virtual ProductEnt Product { get; set; }
    }
}
