//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapperHoneyBadgersWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEnt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderEnt()
        {
            this.OrderItems = new HashSet<OrderItemEnt>();
        }
    
        public int OrderID { get; set; }
        public string Username { get; set; }
        public string OrderAddress { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual AccountEnt Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemEnt> OrderItems { get; set; }
    }
}
